version: '3.8'

services:
  postgres:
    image: postgres:10.4
    restart: always
    container_name: online_store_youtube
    environment:
      - POSTGRES_DB=online-store-youtube
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

